---
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  HANAPRIMARYHOST:
    Description: "SAP HANA Primary Host Instance ID"
    Type: String

  HANASECONDARYHOST:
    Description: "SAP HANA Secondary Host Instance ID"
    Type: String

#  SAPSID:
#    Description: "SAP Instance ID"
#    Type: String
#    Default: HA1
Resources:
  MyDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: HANA-dashboard
      DashboardBody: !Sub |
          {
              "widgets": [
                {
                      "type": "metric",
                      "x": 0,
                      "y": 0,
                      "width": 6,
                      "height": 6,
                      "properties": {
                        "metrics": [
                            [ "Custom", "HANA-Host-Memory-Usage", "Instance", "${HANAPRIMARYHOST}" ],
                            [ "Custom", "HANA-Host-Memory-Usage", "Instance", "${HANASECONDARYHOST}" ]
                        ],
                          "region": "cn-northwest-1",
                          "stat": "Average",
                          "period": 300,
                          "view": "timeSeries",
                          "title": "HANA MemoryUtilization",
                          "stacked": false
                      }
                },
                {
                      "type": "metric",
                      "x": 6,
                      "y": 0,
                      "width": 6,
                      "height": 6,
                      "properties": {
                        "metrics": [
                            [ "Custom", "HANACluster-OIP-Status", "Instance", "${HANAPRIMARYHOST}" ],
                            [ "Custom", "HANACluster-Stonith-Status", "Instance", "${HANAPRIMARYHOST}" ],
                            [ "Custom", "HANACluster-Clone-set-Status", "Instance", "${HANAPRIMARYHOST}" ]
                        ],
                          "region": "cn-northwest-1",
                          "stat": "Average",
                          "period": 300,
                          "view": "timeSeries",
                          "title": "HANA Cluster status Primary Node",
                          "stacked": false
                      }
                },
                {
                      "type": "metric",
                      "x": 12,
                      "y": 0,
                      "width": 6,
                      "height": 6,
                      "properties": {
                        "metrics": [
                            [ "Custom", "HANACluster-OIP-Status", "Instance", "${HANASECONDARYHOST}" ],
                            [ "Custom", "HANACluster-Stonith-Status", "Instance", "${HANASECONDARYHOST}" ],
                            [ "Custom", "HANACluster-Clone-set-Status", "Instance", "${HANASECONDARYHOST}" ]
                        ],
                          "region": "cn-northwest-1",
                          "stat": "Average",
                          "period": 300,
                          "view": "timeSeries",
                          "title": "HANA Cluster status Secondary Node",
                          "stacked": false
                      }
                },
                {
                      "type": "metric",
                      "x": 18,
                      "y": 0,
                      "width": 6,
                      "height": 6,
                      "properties": {
                        "metrics": [
                            [ "Custom", "HANA-Data-Disk-usage", "Instance", "${HANAPRIMARYHOST}" ],
                            [ "Custom", "HANA-Data-Disk-usage", "Instance", "${HANASECONDARYHOST}" ]
                        ],
                          "region": "cn-northwest-1",
                          "stat": "Average",
                          "period": 300,
                          "view": "timeSeries",
                          "title": "HANA database Data disk usage",
                          "stacked": false
                      }
                },
                {
                      "type": "metric",
                      "x": 0,
                      "y": 6,
                      "width": 6,
                      "height": 6,
                      "properties": {
                        "metrics": [
                            [ "AWS/EC2", "CPUUtilization", "InstanceId", "${HANAPRIMARYHOST}" ],
                            [ "AWS/EC2", "CPUUtilization", "InstanceId", "${HANASECONDARYHOST}" ]
                        ],
                          "region": "cn-northwest-1",
                          "stat": "Average",
                          "period": 300,
                          "view": "timeSeries",
                          "title": "SAP and DB Instance CPU utilizaton",
                          "stacked": false
                      }
                },
                {
                      "type": "metric",
                      "x": 6,
                      "y": 6,
                      "width": 6,
                      "height": 6,
                      "properties": {
                        "metrics": [
                            [ "Custom", "HANA-Replication-Status", "Instance", "${HANAPRIMARYHOST}" ],
                            [ "Custom", "HANA-Replication-Status", "Instance", "${HANASECONDARYHOST}" ]
                        ],
                          "region": "cn-northwest-1",
                          "stat": "Average",
                          "period": 300,
                          "view": "timeSeries",
                          "title": "HANA Replication Status",
                          "stacked": false
                      }
                },
                {
                      "type": "metric",
                      "x": 12,
                      "y": 6,
                      "width": 6,
                      "height": 6,
                      "properties": {
                        "metrics": [
                            [ "Custom", "HANA-hdbindexserver", "Instance", "${HANAPRIMARYHOST}" ],
                            [ "Custom", "HANA-hdbindexserver", "Instance", "${HANASECONDARYHOST}" ],
                            [ "Custom", "HANA-hdbdaemon", "Instance", "${HANAPRIMARYHOST}" ],
                            [ "Custom", "HANA-hdbdaemon", "Instance", "${HANASECONDARYHOST}" ],
                            [ "Custom", "HANA-hdbcompileserver", "Instance", "${HANAPRIMARYHOST}" ],
                            [ "Custom", "HANA-hdbcompileserver", "Instance", "${HANASECONDARYHOST}" ],
                            [ "Custom", "HANA-hdbnameserver", "Instance", "${HANAPRIMARYHOST}" ],
                            [ "Custom", "HANA-hdbnameserver", "Instance", "${HANASECONDARYHOST}" ],
                            [ "Custom", "HANA-hdbpreprocessor", "Instance", "${HANAPRIMARYHOST}" ],
                            [ "Custom", "HANA-hdbpreprocessor", "Instance", "${HANASECONDARYHOST}" ],
                            [ "Custom", "HANA-hdbxsengine", "Instance", "${HANAPRIMARYHOST}" ],
                            [ "Custom", "HANA-hdbxsengine", "Instance", "${HANASECONDARYHOST}" ]

                        ],
                          "region": "cn-northwest-1",
                          "stat": "Average",
                          "period": 300,
                          "view": "timeSeries",
                          "title": "HANA Service Status",
                          "stacked": false
                      }
                },
                {
                      "type": "metric",
                      "x": 18,
                      "y": 6,
                      "width": 6,
                      "height": 6,
                      "properties": {
                        "metrics": [
                            [ "Custom", "HANA-Data-Sync-Status", "Instance", "${HANAPRIMARYHOST}" ],
                            [ "Custom", "HANA-Data-Sync-Status", "Instance", "${HANASECONDARYHOST}" ]
                        ],
                          "region": "cn-northwest-1",
                          "stat": "Average",
                          "period": 300,
                          "view": "timeSeries",
                          "title": "HANA Data Sync Status",
                          "stacked": false
                      }
                }
              ]
          }
